export const actionTypes = {
  //DASHBOARD USUARIO
  GET_ESTADISTICAS_USUARIO: "GET_ESTADISTICAS_USUARIO",
  SET_ESTADISTICAS_USUARIO: "SET_ESTADISTICAS_USUARIO",

  //CATEGORIAS
  GET_ALL_CATEGORIAS: "GET_ALL_CATEGORIAS",
  SET_ALL_CATEGORIAS: "SET_ALL_CATEGORIAS",

  //DATA USER
  GET_USUARIO_DATA: "GET_USUARIO_DATA",
  SET_USUARIO_DATA: "SET_USUARIO_DATA",

  //LISTA USERS
  GET_LISTA_USUARIOS: "GET_LISTA_USUARIOS",
  SET_LISTA_USUARIOS: "SET_LISTA_USUARIOS",

  //LOGIN
  VERIFICAR_INGRESO_LOGIN: "VERIFICAR_INGRESO_LOGIN",
  RESULT_VERIFICAR_LOGIN: "RESULT_VERIFICAR_LOGIN",
  SET_LOGIN: "SET_LOGIN",

  //REGISTER
  GET_REGISTRAR_USUARIO: "GET_REGISTRAR_USUARIO",
  SET_REGISTRAR_USUARIO: "SET_REGISTRAR_USUARIO",

  //USER VALIDAR REGISTRO
  USER_VALIDAR_REGISTRO:"USER_VALIDAR_REGISTRO",

  //SET VIDEO
  SET_ENVIAR_VIDEO: "SET_ENVIAR_VIDEO",

  //CONFIRMAR VIDEOS ELIMINADOS
  CONFIRMAR_VIDEOS_ELIMINADOS: "CONFIRMAR_VIDEOS_ELIMINADOS",

  //SET CODIGO VERIFICACION
  SET_ENVIAR_CODIGO_VERIFICACION: "SET_ENVIAR_CODIGO_VERIFICACION",

  //ELIMINAR VIDEO USER
  SET_ELIMINAR_VIDEO_USER: "SET_ELIMINAR_VIDEO_USER",

  //LIST VIDEOS
  GET_RECIBIR_MISVIDEOS: "GET_RECIBIR_MISVIDEOS",
  SET_RECIBIR_MISVIDEOS: "SET_RECIBIR_MISVIDEOS",
  SET_VIDEOS_COMPRADOS: "SET_VIDEOS_COMPRADOS",
  GET_RECIBIR_VIDEOS_COMPRADOS: "GET_RECIBIR_VIDEOS_COMPRADOS",

  // EDITAR PERFIL USUARIO
  EDITAR_USUARIO_PERFIL: "EDITAR_USUARIO_PERFIL",
  RESPUESTA_EDITAR_USUARIO_PERFIL:"RESPUESTA_EDITAR_USUARIO_PERFIL",

  //ENVIAR MAIL AYUDA
  ENVIAR_MAIL_AYUDA: "ENVIAR_MAIL_AYUDA",

  //REENVIAR CODIGO USER
  REENVIAR_CODIGO_USER:"REENVIAR_CODIGO_USER",
  RESPUESTA_REENVIAR_CODIGO:"RESPUESTA_REENVIAR_CODIGO",

  //VEDOR

  //VEDOR ADD PERIODISTA
  VEDOR_AGREGAR_PERIODISTA: "VEDOR_AGREGAR_PERIODISTA",
  SET_RESPUESTA_PERIODISTA:"SET_RESPUESTA_PERIODISTA",
  //VEDOR LISTA PERIODISTAS
  SET_LISTA_PERIODISTA: "SET_LISTA_PERIODISTA",
  GET_LISTA_PERIODISTA: "GET_LISTA_PERIODISTA",
  //VEDOR DELETE PERIODISTA
  DELETE_PERIODISTA: "DELETE_PERIODISTA",

  //CREDENCIALES MERCADO PAGO
  SET_RECIBIR_CREDENCIALES_MP: "SET_RECIBIR_CREDENCIALES_MP",
  GET_RECIBIR_CREDENCIALES_MP: "GET_RECIBIR_CREDENCIALES_MP",

  //ELIMINAR CREDENCIALES MP
  ELIMINAR_CREDENCIALES_MP: "ELIMINAR_CREDENCIALES_MP",

  // ACTIVAR NAVLINK SIDEBAR
  ACTIVAR_SECCION_SIDEBAR: "ACTIVAR_SECCION_SIDEBAR",
  DESACTIVAR_SECCION_SIDEBAR: "DESACTIVAR_SECCION_SIDEBAR",

  // VEEDOR RECIBIR VIDEOS
  SET_VEEDOR_RECIBIR_VIDEOS: "SET_VEEDOR_RECIBIR_VIDEOS",
  GET_VEEDOR_RECIBIR_VIDEOS: "GET_VEEDOR_RECIBIR_VIDEOS",

  //LISTA PERIODISTAS DISPONIBLES
  SET_LISTA_PERIODISTA_DISPONIBLES: "SET_LISTA_PERIODISTA_DISPONIBLES",
  GET_LISTA_PERIODISTA_DISPONIBLES: "GET_LISTA_PERIODISTA_DISPONIBLES",

  //ELIMINAR PERIODISTAS
  SET_ELIMINAR_PERIODISTA: 'SET_ELIMINAR_PERIODISTA',
  ACTUALIZAR_ELIMINAR_PERIODISTA: 'ACTUALIZAR_ELIMINAR_PERIODISTA',

  //RECIBIR VIDEOS COMPRADOS
  SET_VEEDOR_RECIBIR_VIDEOS_COMPRADOS: "SET_VEEDOR_RECIBIR_VIDEOS_COMPRADOS",
  GET_VEEDOR_RECIBIR_VIDEOS_COMPRADOS: "GET_VEEDOR_RECIBIR_VIDEOS_COMPRADOS",

  //RECIBIR VIDEOS GUARDADOS
  SET_VEEDOR_RECIBIR_VIDEOS_GUARDADOS: "SET_VEEDOR_RECIBIR_VIDEOS_GUARDADOS",
  GET_VEEDOR_RECIBIR_VIDEOS_GUARDADOS: "GET_VEEDOR_RECIBIR_VIDEOS_GUARDADOS",

  //RECIBIR VIDEOS GUARDADOS
  SET_VEEDOR_RECIBIR_VIDEOS_TENDENCIAS: "SET_VEEDOR_RECIBIR_VIDEOS_TENDENCIAS",
  GET_VEEDOR_RECIBIR_VIDEOS_TENDENCIAS: "GET_VEEDOR_RECIBIR_VIDEOS_TENDENCIAS",

  //RECIBIR VIDEOS DESCARTADOS
  SET_VEEDOR_RECIBIR_VIDEOS_DESCARTADOS: "SET_VEEDOR_RECIBIR_VIDEOS_DESCARTADOS",
  GET_VEEDOR_RECIBIR_VIDEOS_DESCARTADOS: "GET_VEEDOR_RECIBIR_VIDEOS_DESCARTADOS",

  //RECIBIR VIDEOS DESTACADOS
  SET_VEEDOR_RECIBIR_VIDEOS_DESTACADOS: "SET_VEEDOR_RECIBIR_VIDEOS_DESTACADOS",
  GET_VEEDOR_RECIBIR_VIDEOS_DESTACADOS: "GET_VEEDOR_RECIBIR_VIDEOS_DESTACADOS",

  AVANZAR_VIDEO_POST_COMPRA:"AVANZAR_VIDEO_POST_COMPRA",

  //VIDEO VISTO
  SET_VIDEO_VISTO: "SET_VIDEO_VISTO",

  // VEEDOR ACCIONES DE VIDEO
  SET_ELIMINAR_VIDEO: "SET_ELIMINAR_VIDEO",
  SET_REPRODUCTOR_VIDEO_ACTUALIZAR_VISTA: "SET_REPRODUCTOR_VIDEO_ACTUALIZAR_VISTA",
  SET_GUARDAR_VIDEO: "SET_GUARDAR_VIDEO",
  SET_COMPRAR_VIDEO: "SET_COMPRAR_VIDEO",

  // LISTA LOCALIDADES
  SET_LISTA_LOCALIDADES: "SET_LISTA_LOCALIDADES",
  GET_LISTA_LOCALIDADES: "GET_LISTA_LOCALIDADES",

  // LISTA PROVINCIAS
  SET_LISTA_PROVINCIAS: "SET_LISTA_PROVINCIAS",
  GET_LISTA_PROVINCIAS: "GET_LISTA_PROVINCIAS",

  // ENVIAR MAIL PERIODISTA
  ENVIAR_MAIL_PERIODISTA:"ENVIAR_MAIL_PERIODISTA",
  RESPUESTA_MAIL_PERIODISTA:"RESPUESTA_MAIL_PERIODISTA",



  // SUPER ADMIN

  // LISTA VEEDORES
  GET_LISTA_VEEDORES: "GET_LISTA_VEEDORES",
  SET_LISTA_VEEDORES: "SET_LISTA_VEEDORES",

  // LISTA USER CON VIDEOS
  GET_LISTA_USERS_CON_VIDEOS: "GET_LISTA_USERS_CON_VIDEOS",
  SET_LISTA_USERS_CON_VIDEOS: "SET_LISTA_USERS_CON_VIDEOS",

  // LISTA VIDEOS POR USUARIO
  GET_VIDEOS_POR_USUARIO: "GET_VIDEOS_POR_USUARIO",
  SET_VIDEOS_POR_USUARIO: "SET_VIDEOS_POR_USUARIO",

  // RECIBIR VIDEOS ADMIN
  SET_ADMIN_RECIBIR_VIDEOS: "SET_ADMIN_RECIBIR_VIDEOS",
  GET_ADMIN_RECIBIR_VIDEOS: "GET_ADMIN_RECIBIR_VIDEOS",

  // RECIBIR VIDEOS ADMIN ADQUIRIDOS
  SET_ADMIN_RECIBIR_VIDEOS_COMPRADOS: "SET_ADMIN_RECIBIR_VIDEOS_COMPRADOS",
  GET_ADMIN_RECIBIR_VIDEOS_COMPRADOS: "GET_ADMIN_RECIBIR_VIDEOS_COMPRADOS",

  // RECIBIR VIDEOS ADMIN ADQUIRIDOS
  SET_ADMIN_RECIBIR_VIDEOS_GUARDADOS: "SET_ADMIN_RECIBIR_VIDEOS_GUARDADOS",
  GET_ADMIN_RECIBIR_VIDEOS_GUARDADOS: "GET_ADMIN_RECIBIR_VIDEOS_GUARDADOS",

  // RECIBIR VIDEOS ADMIN DESTACADOS
  SET_ADMIN_RECIBIR_VIDEOS_DESTACADOS: "SET_ADMIN_RECIBIR_VIDEOS_DESTACADOS",
  GET_ADMIN_RECIBIR_VIDEOS_DESTACADOS: "GET_ADMIN_RECIBIR_VIDEOS_DESTACADOS",

  // RECIBIR VIDEOS ADMIN DESCARTADOS
  SET_ADMIN_RECIBIR_VIDEOS_DESCARTADOS: "SET_ADMIN_RECIBIR_VIDEOS_DESCARTADOS",
  GET_ADMIN_RECIBIR_VIDEOS_DESCARTADOS: "GET_ADMIN_RECIBIR_VIDEOS_DESCARTADOS",

  //USER UTILIZO_FILTROS
  GET_USER_UTILIZO_FILTROS: "GET_USER_UTILIZO_FILTROS",


  //LISTA ESTADISTICAS
  GET_LISTA_ESTADISTICAS: "GET_LISTA_ESTADISTICAS",
  SET_LISTA_ESTADISTICAS: "SET_LISTA_ESTADISTICAS",

  //NOTIFICACIONES USER
  GET_LISTA_NOTIFICACIONES_USER: "GET_LISTA_NOTIFICACIONES_USER",
  SET_LISTA_NOTIFICACIONES_USER: "SET_LISTA_NOTIFICACIONES_USER",
  //ESTADO NOTIFICACIONES
  SET_ESTADO_NOTIFICACIONES: "SET_ESTADO_NOTIFICACIONES",
  //RESPUESTA NOTIFICACIONES
  SET_RESPUESTA_NOTIFICACIONES: "SET_RESPUESTA_NOTIFICACIONES",
  
  VERIFICAR_INGRESO_LOGIN: "VERIFICAR_INGRESO_LOGIN",
  
  //Actulizacion strikes
  GET_SUMAR_STRIKE: "GET_SUMAR_STRIKE",
  SET_SUMAR_STRIKE: "SET_SUMAR_STRIKE",

  //Actulizacion strikes
  GET_MERCADOPAGO_DATA: "GET_MERCADOPAGO_DATA",
  SET_MERCADOPAGO_DATA: "SET_MERCADOPAGO_DATA",
};
